apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: teste
  namespace: meudominio-dev
spec:
  gateways:
  - istio-ingress/gw-https
  hosts:
  - teste.meudominio.com.br
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: teste
        port:
          number: 8080
